### ISSUE TITLE
Caused by: java.lang.NoClassDefFoundError: teamroots/embers/api/alchemy/AspectList$AspectRangeList

### ISSUE THREAD

**Issue by gravestristen** [EpicSquid/Embers#36]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  MalisisCorePlugin (malisiscore-1.12.2-6.4.0.jar)
  FarseekCoreMod (Farseek-1.12-2.3.1.jar)
  OpenEyePlugin (OpenEye-1.12.2-0.8.jar)
  BlurPlugin (Blur-1.0.4-14.jar)
  Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.3-1.12.2.jar)
  BetterFoliageLoader (BetterFoliage-MC1.12-2.2.0.jar)
  DynamicSurroundingsCore (DynamicSurroundings-core-1.12.2-3.4.10.5.jar)
  ForgelinPlugin (Forgelin-1.8.2.jar)
  SSLoadingPlugin (SereneSeasons-1.12.2-1.2.13-universal.jar)
  HCASM (HammerCore-1.12.2-2.0.4.1.jar)
Contact their authors BEFORE contacting forge

// Uh... Did I do that?

Time: 12/22/18 12:56 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from CraftTweaker2 (crafttweaker)
Caused by: java.lang.NoClassDefFoundError: teamroots/embers/api/alchemy/AspectList$AspectRangeList
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.getDeclaredMethods(Class.java:1975)
	at crafttweaker.CraftTweakerAPI.registerClass(CraftTweakerAPI.java:237)
	at crafttweaker.mc1120.CraftTweaker.lambda$onPreInitialization$0(CraftTweaker.java:103)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at crafttweaker.mc1120.CraftTweaker.onPreInitialization(CraftTweaker.java:95)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:624)
	at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:627)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: teamroots.embers.api.alchemy.AspectList$AspectRangeList
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 47 more
Caused by: java.lang.NullPointerException

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Mac OS X (x86_64) version 10.14.2
	Java Version: 1.8.0_74, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 346555472 bytes (330 MB) / 805306368 bytes (768 MB) up to 4294967296 bytes (4096 MB)
	JVM Flags: 7 total; -Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2796 Optifine OptiFine_1.12.2_HD_U_E3 85 mods loaded, 85 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                   | Version                  | Source                                            | Signature                                |
	|:----- |:-------------------- |:------------------------ |:------------------------------------------------- |:---------------------------------------- |
	| LCH   | minecraft            | 1.12.2                   | minecraft.jar                                     | None                                     |
	| LCH   | mcp                  | 9.42                     | minecraft.jar                                     | None                                     |
	| LCH   | FML                  | 8.0.99.99                | forge-1.12.2-14.23.5.2796.jar                     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | forge                | 14.23.5.2796             | forge-1.12.2-14.23.5.2796.jar                     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | OpenEye              | 0.8                      | OpenEye-1.12.2-0.8.jar                            | None                                     |
	| LCH   | foamfixcore          | 7.7.4                    | minecraft.jar                                     | None                                     |
	| LCH   | dsurroundcore        |                          | minecraft.jar                                     | None                                     |
	| LCH   | embers               | 0.230                    | embers-0.230.jar                                  | None                                     |
	| LCH   | aetherworks          | 1.12.2-1.0.0.3           | AetherWorks-1.12.2-1.0.0.3.jar                    | None                                     |
	| LCH   | antiqueatlas         | 4.4.9                    | antiqueatlas-1.12.2-4.4.9.jar                     | None                                     |
	| LCH   | antiqueatlasoverlay  | 1.2                      | antiqueatlas-1.12.2-4.4.9.jar                     | None                                     |
	| LCH   | examplemod           | 1.0                      | antiqueatlas-1.12.2-4.4.9.jar                     | None                                     |
	| LCH   | atlasextras          | 1.2                      | AtlasExtras-1.12.2-1.2.1.jar                      | None                                     |
	| LCH   | atlcraft             | MC1.12-Ver1.9            | ATLCraftCandlesMod(MC1.12-Ver1.9).jar             | None                                     |
	| LCH   | mcmultipart          | 2.5.3                    | MCMultiPart-2.5.3.jar                             | None                                     |
	| LCH   | sonarcore            | 5.0.19                   | sonarcore-1.12.2-5.0.19-20.jar                    | None                                     |
	| LCH   | bagelsmore           | 2.0.1                    | bagelsmore-1.12.2-2.0.1.jar                       | None                                     |
	| LCH   | baubles              | 1.5.2                    | Baubles-1.12-1.5.2.jar                            | None                                     |
	| LCH   | betteradvancements   | 0.0.5.17                 | BetterAdvancements-1.12.2-0.0.5.17.jar            | None                                     |
	| LCH   | forgelin             | 1.8.2                    | Forgelin-1.8.2.jar                                | None                                     |
	| LCH   | betterfoliage        | 2.2.0                    | BetterFoliage-MC1.12-2.2.0.jar                    | None                                     |
	| LCH   | biomesoplenty        | 7.0.1.2402               | BiomesOPlenty-1.12.2-7.0.1.2402-universal.jar     | None                                     |
	| LCH   | jei                  | 4.13.1.225               | jei_1.12.2-4.13.1.225.jar                         | None                                     |
	| LCH   | blockdrops           | 1.4.0                    | blockdrops-1.12.2-1.4.0.jar                       | None                                     |
	| LCH   | blur                 | 1.0.4-14                 | Blur-1.0.4-14.jar                                 | None                                     |
	| LCH   | bullseye             | 3.0.7                    | Bullseye-1.12.2-3.0.7.jar                         | None                                     |
	| LCH   | chineseworkshop      | 1.2.5                    | ChineseWorkshop-1.12.2_1.2.5.jar                  | None                                     |
	| LCH   | toughasnails         | 3.1.0.139                | ToughAsNails-1.12.2-3.1.0.139-universal.jar       | None                                     |
	| LCH   | comforts             | 1.4.1                    | comforts-1.12.2-1.4.1.jar                         | 5d5b8aee896a4f5ea3f3114784742662a67ad32f |
	| LCE   | crafttweaker         | 4.1.10                   | CraftTweaker2-1.12-4.1.10.jar                     | None                                     |
	| LC    | ctgui                | 1.0.0                    | CraftTweaker2-1.12-4.1.10.jar                     | None                                     |
	| LC    | crafttweakerjei      | 2.0.2                    | CraftTweaker2-1.12-4.1.10.jar                     | None                                     |
	| LC    | essentials           | 1.12.2-1.2.0             | essentials-1.12.2-1.2.0.jar                       | None                                     |
	| LC    | crossroads           | 1.12.2-1.11.2            | crossroads-1.12.2-1.11.2.jar                      | None                                     |
	| LC    | ptrmodellib          | 1.0.3                    | PTRLib-1.0.3.jar                                  | None                                     |
	| LC    | props                | 2.6.2                    | Decocraft-2.6.2_1.12.2.jar                        | None                                     |
	| LC    | dynamictrees         | 1.12.2-0.9.1d            | DynamicTrees-1.12.2-0.9.1d.jar                    | None                                     |
	| LC    | dynamictreesbop      | 1.12.2-1.4.1d            | DynamicTreesBOP-1.12.2-1.4.1d.jar                 | None                                     |
	| LC    | harvestcraft         | 1.12.2z                  | Pam's+HarvestCraft+1.12.2za.jar                   | None                                     |
	| LC    | dynamictreesphc      | 1.12.2-0.1.1a            | DynamicTreesPHC-1.12.2-0.1.1a.jar                 | None                                     |
	| LC    | extraalchemy         | 0.3.8.6.1-release        | extraalchemy-0.3.8.6.1-release.jar                | None                                     |
	| LC    | familiarfauna        | 1.0.11                   | FamiliarFauna-1.12.2-1.0.11.jar                   | None                                     |
	| LC    | fbp                  | 2.4.1                    | FancyBlockParticles-1.12.x-2.4.1.jar              | None                                     |
	| LC    | farseek              | 2.3.1                    | Farseek-1.12-2.3.1.jar                            | None                                     |
	| LC    | fenceoverhaul        | 1.3.4                    | FenceOverhaul-1.3.4.jar                           | None                                     |
	| LC    | foamfix              | 0.10.3-1.12.2            | foamfix-0.10.3-1.12.2.jar                         | None                                     |
	| LC    | rustic               | 1.0.12                   | rustic-1.0.12.jar                                 | None                                     |
	| LC    | primal               | 0.6.104                  | PrimalCore-1.12.2-0.6.104.jar                     | 67a0e286dc0d4b502f3c92ac20b953517b52d0a9 |
	| LC    | forgecraft           | 1.6.42                   | ForgeCraft-1.6.42.jar                             | None                                     |
	| LC    | guideapi             | 1.12-2.1.8-63            | Guide-API-1.12-2.1.8-63.jar                       | None                                     |
	| LC    | hammercore           | 2.0.4.1                  | HammerCore-1.12.2-2.0.4.1.jar                     | 4d7b29cd19124e986da685107d16ce4b49bc0a97 |
	| LC    | improvableskills     | 3.5.9r                   | ImprovableSkills-1.12.2-3.5.9r.jar                | 4d7b29cd19124e986da685107d16ce4b49bc0a97 |
	| LC    | industrialrenewal    | 0.8.0                    | IndustrialRenewal_1.12.2-0.8.0.jar                | None                                     |
	| LC    | inventoryneko        | ${version}               | InventoryNeko-0.1.0.jar                           | None                                     |
	| LC    | jehc                 | 1.12.2                   | JEHC-1.12.2-1.6.2.0.jar                           | None                                     |
	| LC    | jeivillagers         | 1.0                      | jeivillagers-1.12-1.0.2.jar                       | None                                     |
	| LC    | jeresources          | 0.8.5.27                 | JustEnoughResources-1.12.2-0.8.5.27.jar           | None                                     |
	| LC    | jeroreintegration    | 1.1.0                    | JEROreIntegration-1.12.2-1.1.0.jar                | None                                     |
	| LC    | journeymap           | 1.12.2-5.5.3             | journeymap-1.12.2-5.5.3.jar                       | None                                     |
	| LC    | jarm                 | 1.1.1                    | Just+A+Raft+Mod-1.1.1.jar                         | None                                     |
	| LC    | lsc                  | 0.6.1.2-alpha            | Loot+Slash+Conquer-1.12.2-0.6.1.2-alpha.jar       | None                                     |
	| LC    | lunatriuscore        | 1.2.0.42                 | LunatriusCore-1.12.2-1.2.0.42-universal.jar       | None                                     |
	| LC    | malisiscore          | 1.12.2-6.4.0             | malisiscore-1.12.2-6.4.0.jar                      | None                                     |
	| LC    | malisisdoors         | 1.12.2-7.3.0             | malisisdoors-1.12.2-7.3.0.jar                     | None                                     |
	| LC    | mobends              | 0.24                     | mobends-0.24_for_MC-1.12.jar                      | None                                     |
	| LC    | placeableitems       | 3.3                      | placeableitems-3.3.jar                            | None                                     |
	| LC    | prefab               | 1.3.0.25                 | prefab-1.3.0.25.jar                               | None                                     |
	| LC    | realdrops            | 1.2.14                   | RealisticItemDrops-1.2.14.jar                     | None                                     |
	| LC    | additionalstructures | 1.8.0                    | Rex's+Additional+Structures+1.12.2++(v.1.8.0).jar | None                                     |
	| LC    | sereneseasons        | 1.2.13                   | SereneSeasons-1.12.2-1.2.13-universal.jar         | None                                     |
	| LC    | signpost             | 1.06.1                   | signpost-1.12-1.06.1.jar                          | None                                     |
	| LC    | soot                 | 1.3hotfix                | Soot-1.3hotfix.jar                                | None                                     |
	| LC    | soundfilters         | 0.10_for_1.12            | SoundFilters-0.10_for_1.12.jar                    | None                                     |
	| LC    | steamworld           | 0.4.0.2                  | SteamWorld+1.12.2-0.4.0.2.jar                     | None                                     |
	| LC    | streams              | 0.4.4                    | Streams-1.12-0.4.4.jar                            | None                                     |
	| LC    | tanspit              | 1.12.2-1.3               | tanspit-1.12.2-1.3.jar                            | None                                     |
	| LC    | thebomplugin         | 1.12-0.2.3               | thebomplugin-1.12-0.2.3.jar                       | None                                     |
	| LC    | vimmersion           | 2.0.3.3                  | vanilla-immersion-1.12.2-2.0.3.3.jar              | 6c67ec97cb96c64a0bbd82a3cb1ec48cbde61bb2 |
	| LC    | viesmachines         | 0.11.16-beta - MC 1.12.2 | viesmachines-1.12.2-0.11.16-beta.jar              | None                                     |
	| LC    | waddles              | 0.6.0                    | Waddles-1.12.2-0.6.0.jar                          | None                                     |
	| LC    | walljump             | 1.12.2-1.2.1             | walljump-1.12.2-1.2.1.jar                         | None                                     |
	| LC    | waystones            | 4.0.67                   | Waystones_1.12.2-4.0.67.jar                       | None                                     |
	| LC    | wearablebackpacks    | 3.1.3                    | WearableBackpacks-1.12.2-3.1.3.jar                | None                                     |
	| LC    | dsurround            | 3.4.10.5                 | DynamicSurroundings-1.12.2-3.4.10.5.jar           | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
	| LC    | presets              | 3.4.10.5                 | DynamicSurroundings-1.12.2-3.4.10.5.jar           | None                                     |

	Loaded coremods (and transformers): 
MalisisCorePlugin (malisiscore-1.12.2-6.4.0.jar)
  
FarseekCoreMod (Farseek-1.12-2.3.1.jar)
  farseek.core.FarseekClassTransformer
OpenEyePlugin (OpenEye-1.12.2-0.8.jar)
  openeye.asm.MultiTransformer
BlurPlugin (Blur-1.0.4-14.jar)
  com.tterrag.blur.BlurTransformer
Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.3-1.12.2.jar)
  pl.asie.foamfix.coremod.FoamFixTransformer
BetterFoliageLoader (BetterFoliage-MC1.12-2.2.0.jar)
  mods.betterfoliage.loader.BetterFoliageTransformer
DynamicSurroundingsCore (DynamicSurroundings-core-1.12.2-3.4.10.5.jar)
  org.blockartistry.DynSurround.asm.Transformer
ForgelinPlugin (Forgelin-1.8.2.jar)
  
SSLoadingPlugin (SereneSeasons-1.12.2-1.2.13-universal.jar)
  sereneseasons.asm.transformer.EntityRendererTransformer
  sereneseasons.asm.transformer.WorldTransformer
HCASM (HammerCore-1.12.2-2.0.4.1.jar)
  com.zeitheron.hammercore.asm.HammerCoreTransformer
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '2.1 ATI-2.4.9' Renderer: 'AMD Radeon Pro 560 OpenGL Engine'
	Hammer Core Information: FluidDictionary Info: Registered 2 fluids.
OreDictionary Info: Registered 222 names; 473 stacks.
Pastebin Connection: Okay.
Dependent Mods:
    -Improvable Skills (improvableskills) @3.5.9r

	OptiFine Version: OptiFine_1.12.2_HD_U_E3
	OptiFine Build: 20181210-121000
	Render Distance Chunks: 12
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: Sildurs_Vibrant_Shaders_v1.18_Extreme-VL.zip
	OpenGlVersion: 2.1 ATI-2.4.9
	OpenGlRenderer: AMD Radeon Pro 560 OpenGL Engine
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 4

**Comment by DaedalusGame** [comment]
![grafik](https://user-images.githubusercontent.com/9559216/50377378-8fa02980-061c-11e9-810b-d3ffe904ab35.png)

**Comment by gravestristen** [comment]
both ember and embers rekindled?
